const express = require('express')
const verifyAuth = require('../middleware/common/verifyAuth')
const authRouter = require('./auth')
const attributeRouter = require('./collections/attribute')
const categoryRouter = require('./collections/category')
const faqRouter = require('./collections/faq')
const mediaRouter = require('./collections/media')
const reviewRouter = require('./collections/review')
const sellingChannelRouter = require('./collections/sellingChannel')
const priceListRouter = require('./collections/priceList')
const snippetRouter = require('./collections/snippet')
const tagRouter = require('./collections/tag')
const loginRouter = require('./login')
const productRouter = require('./product')
const roleRouter = require('./role')
const teamRouter = require('./team')
const uploadRouter = require('./upload')
const userRouter = require('./user')

const routerV1 = express.Router()

routerV1.use('/authentication', authRouter)
routerV1.use('/login', loginRouter)
routerV1.use('/user', userRouter)
routerV1.use('/team', verifyAuth, teamRouter)
routerV1.use('/role', verifyAuth, roleRouter)
routerV1.use('/product', productRouter)
routerV1.use('/upload', uploadRouter)
routerV1.use('/collections/category', verifyAuth, categoryRouter)
routerV1.use('/collections/attribute', verifyAuth, attributeRouter)
routerV1.use('/collections/tag', verifyAuth, tagRouter)
routerV1.use('/collections/media-category', verifyAuth, mediaRouter)
routerV1.use('/collections/snippet', verifyAuth, snippetRouter)
routerV1.use('/collections/faq', verifyAuth, faqRouter)
routerV1.use('/collections/review', verifyAuth, reviewRouter)
routerV1.use('/collections/selling-channel', verifyAuth, sellingChannelRouter)
routerV1.use('/collections/price-list', verifyAuth, priceListRouter)

module.exports = routerV1
